CREATE TABLE IF NOT EXISTS applications (
    application_id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    application_type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP WITH TIME ZONE,
    processed_by_user_id INTEGER REFERENCES users(user_id),
    applicant_name VARCHAR(255) NOT NULL,
    applicant_id_document_type VARCHAR(50),
    property_address TEXT NOT NULL,
    installation_number VARCHAR(50),
    dask_policy_number VARCHAR(50),
    is_tenant BOOLEAN NOT NULL DEFAULT false,
    landlord_full_name VARCHAR(255),
    landlord_id_type VARCHAR(50),
    landlord_id_number VARCHAR(50),
    landlord_company_name VARCHAR(255),
    landlord_representative_name VARCHAR(255),
    power_of_attorney_provided BOOLEAN NOT NULL DEFAULT false,
    signature_circular_provided BOOLEAN NOT NULL DEFAULT false,
    termination_iban VARCHAR(50),
    ownership_document_type VARCHAR(50),
    notes TEXT,
+   old_bill_file_data BYTEA,
+   proxy_document_data BYTEA,
+   dask_policy_file_data BYTEA,
+   ownership_document_data BYTEA
);